name: CI - Phase 1 (Static Analysis)

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  static-analysis:
    name: Lint & Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm" # Speeds up future runs by caching node_modules

      - name: Install Dependencies
        run: npm ci # 'ci' is faster and more reliable than 'install' in pipelines

      - name: 1. Verify Formatting (Prettier)
        run: npm run format:check

      - name: 2. Run Linter (ESLint)
        run: npm run lint

      - name: 3. Type Check (TSC)
        run: npm run type-check

      - name: 4.settlement service test (Jest)
        run: npm test tests/settlement.service.test.ts
        working-directory: ./trip-planner-backend


      - name: Secret Scanner
        uses: trufflesecurity/trufflehog@main
        with:
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
